# @package _group_

pretrained_weights: null
relative_loss_coef: 0.1

batch_size: 64

lightning_trainer:
    max_epochs: 50

optimize:
    encoder:
        optimizer_type: Adam # Maybe AdamW?????
        weight_decay: 0.01
        scheduler_type: BertScheduler
        warmup_steps: 0
        hold_steps: 0
        decay_steps: 100000 # 1.0 TODO: Fix
        max_lr: 0.000001
        min_lr: 0.00000001

    coord_head:
        optimizer_type: Adam # Maybe AdamW?????
        weight_decay: 0.01 # TOO HIGH???
        scheduler_type: 'BertScheduler'   # BaseScheduler, ChrisScheduler, BertScheduler
        warmup_steps: 500 # 0.005 TODO: fix
        hold_steps: 100 # 0.001 TODO: Fix
        decay_steps: 90000 # 0.9 TODO: Fix
        max_lr: 0.00004
        min_lr: 0.00000001

wandb:
    project: spatial-temporal-control