pretrained_weights: null
gmm_loss_coef: 1.0
relative_loss_coef: 1.0

batch_size: 128

lightning_trainer:
    # max_epochs: 60
    max_steps: 8000
    log_every_n_steps: 10

optimize:
    encoder:
        optimizer_type: AdamW # Maybe AdamW?????
        weight_decay: 0.01
        scheduler_type: BertScheduler
        warmup_ratio: 0
        hold_ratio: 0
        decay_ratio: 1.0
        max_lr: 0.000001
        min_lr: 0.00000001

    coord_head:
        optimizer_type: Adam # Maybe AdamW?????
        weight_decay: 0.01 # TODO: Try 0.001
        scheduler_type: 'BertScheduler'
        warmup_ratio: 0.005
        hold_ratio: 0.001
        decay_ratio: 0.9
        max_lr: 0.00004
        min_lr: 0.00000001

wandb:
    project: spatial-temporal-control