radius: 0.2
num_inference_steps: 50
guidance_scale: 7.5
diffusion_model: runwayml/stable-diffusion-v1-5

optimization:
  num_steps: 5
  weight_initialize_coef: 5.0
  gradient_checkpointing_block_size: 1
  optimizer_type: Adam
  optimizer_kwargs:
    lr: 0.005

layout_predictor:
  cfg_path: layout_predictor/configs/model/replicate.yaml
  model_path: layout_predictor/checkpoints/epoch=68-step=4000.ckpt

loss:
  clip_model: openai/clip-vit-base-patch32
  local_loss_coef: 5.0