# @package _group_

hidden_size: 768
gmm_head:
    num_components: 5
    temperature: 1.
    greedy: True
 
encoder: 
    REL_GT: False
    VOCAB_SIZE: 206
    OBJ_CLASSES_SIZE: 155
    HIDDEN_SIZE: 768
    NUM_LAYERS: 4
    ATTN_HEADS: 4
    DROPOUT: 0.1

DECODER:
    HEAD_TYPE: 'GMM' # 'GMM', 'Linear'
    BOX_LOSS: 'PDF' # for 'GMM' -> 'PDF', for 'Linear' -> 'Reg'
    SCHEDULE_SAMPLE: False
    TWO_PATH: False
    GLOBAL_FEATURE: True
    GREEDY: True
    XY_TEMP: 1.
    WH_TEMP: 1.