from mml_project.layout_predictor.model.coord_head import Coord2DHead
from mml_project.layout_predictor.model.roberta_modified import RobertaEncoder
from mml_project.layout_predictor.model.text2coord import Text2Coord